[features]
seeds = false
[programs.devnet]
solbin = "HTzsNmejt7QRqcotnrKEZJaRqyBMnqsKykeFeQWhxdS2"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/cdjk/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
